# Generated by Django 4.1 on 2022-05-06 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_auto_20220506_1612'),
    ]

    operations = [
    ]
